document.writeln( '<hr size=1 width="750" noshade>' );
document.writeln( '<table cellpadding=0 cellspacing=0 border=0 width="750">' );
document.writeln( '<tr><td>' );
document.writeln( '<table cellpadding=1 cellspacing=0 border=0 width="100%">' );
document.writeln( '<tr><td>' );
document.writeln( '<table cellpadding=2 cellspacing=0 border=0 width="100%">' );
document.writeln( '<tr><td align=center>' );
document.writeln( '<font face="arial" size=-1>' );
document.writeln( '<b>Yahoo! Movies</b>:' );
document.writeln( '<a href="http://us.rd.yahoo.com/movies/bottomtrough/intheaters/?http://movies.yahoo.com/movies/feature/thisweekend.html">In Theaters</a>' );
document.writeln( '- <a href="http://us.rd.yahoo.com/movies/bottomtrough/showtimes/?http://movies.yahoo.com/showtimes/showtimes.html">Times & Tickets</a>' );
document.writeln( '- <a href="http://us.rd.yahoo.com/movies/bottomtrough/greg/?http://movies.yahoo.com/upcoming">Greg&#039;s Previews</a>' );
document.writeln( '- <a href="http://us.rd.yahoo.com/movies/bottomtrough/trailers/?http://movies.yahoo.com/trailers">Trailers</a>' );
document.writeln( '- <a href="http://us.rd.yahoo.com/movies/bottomtrough/moviesshopping/?http://movies.yahoo.com/dvd/">DVD/Video</a>' );
document.writeln( '- <a href="http://us.rd.yahoo.com/movies/bottomtrough/movienews/?http://movies.yahoo.com/news/main/">News & Gossip</a>' );
document.writeln( '- <a href="http://us.rd.yahoo.com/movies/bottomtrough/boxoffice/?http://movies.yahoo.com/boxoffice/latest/rank.html">Box Office</a>' );
document.writeln( '- <a href="http://us.rd.yahoo.com/movies/bottomtrough/moviesmain/?http://movies.yahoo.com">more...</a>' );
document.writeln( '<br><b>Yahoo! Entertainment</b>:' );
document.writeln( '<a href="http://us.rd.yahoo.com/entertainment/bottomtrough/more/?http://movies.yahoo.com">Movies</a>' );
document.writeln( '- <a href="http://us.rd.yahoo.com/entertainment/bottomtrough/music/?http://music.yahoo.com">Music</a>' );
document.writeln( '- <a href="http://us.rd.yahoo.com/entertainment/bottomtrough/tv/?http://tv.yahoo.com">TV</a>' );
document.writeln( '- <a href="http://us.rd.yahoo.com/entertainment/bottomtrough/games/?http://games.yahoo.com">Games</a>' );
document.writeln( '- <a href="http://us.rd.yahoo.com/entertainment/bottomtrough/astrology/?http://astrology.yahoo.com">Astrology</a>' );
document.writeln( '- <a href="http://us.rd.yahoo.com/entertainment/bottomtrough/more/?http://entertainment.tv.yahoo.com">more...</a>' );
document.writeln( '</font>' );
document.writeln( '</td></tr>' );
document.writeln( '</table>' );
document.writeln( '</td></tr>' );
document.writeln( '</table>' );
document.writeln( '</td></tr>' );
document.writeln( '</table>' );
