document.writeln( '<!-- tabs -->' );
document.writeln( '<table cellpadding=0 cellspacing=0 border=0 width=750><tr><td>' );
document.writeln( '<table cellpadding=0 cellspacing=0 border=0 width=750>' );
document.writeln( '<form method="get" action="http://movies.yahoo.com/mv/search">' );
document.writeln( '<tr>' );
document.writeln( '<td width=8 rowspan=2><spacer type=block width=1 height=1></td>' );
document.writeln( '<td width=3 rowspan=2><img src=http://us.i1.yimg.com/us.yimg.com/i/us/mov/el/n-on-left.gif width=3 height=30 alt=""></td><td width=1 height=1 bgcolor=234179><spacer type=block width=1 height=1></td><td width=3 rowspan=2><img src=http://us.i1.yimg.com/us.yimg.com/i/us/mov/el/n-on-right.gif width=3 height=30 alt=""></td><td width=5 rowspan=2><spacer type=block width=1 height=1></td>' );
document.writeln( '<td width=3 rowspan=2><img src=http://us.i1.yimg.com/us.yimg.com/i/us/mov/el/n-off-left.gif width=3 height=30 alt=""></td><td width=1 height=1 bgcolor=666666><spacer type=block width=1 height=1></td><td width=3 rowspan=2><img src=http://us.i1.yimg.com/us.yimg.com/i/us/mov/el/n-off-right.gif width=3 height=30 alt=""></td><td width=5 rowspan=2><spacer type=block width=1 height=1></td>' );
document.writeln( '<td width=3 rowspan=2><img src=http://us.i1.yimg.com/us.yimg.com/i/us/mov/el/n-off-left.gif width=3 height=30 alt=""></td><td width=1 height=1 bgcolor=666666><spacer type=block width=1 height=1></td><td width=3 rowspan=2><img src=http://us.i1.yimg.com/us.yimg.com/i/us/mov/el/n-off-right.gif width=3 height=30 alt=""></td><td width=5 rowspan=2><spacer type=block width=1 height=1></td>' );
document.writeln( '<td><spacer type=block width=1 height=1></td>' );
document.writeln( '</tr>' );
document.writeln( '<tr>' );
document.writeln( '<td bgcolor=4B6DAD align=center>&nbsp;<a href="http://us.rd.yahoo.com/movies/navbar/top/movies/?http://movies.yahoo.com" class=mainon><b>Movies</b></a>&nbsp;</td>' );
document.writeln( '<td align=center background="http://us.i1.yimg.com/us.yimg.com/i/us/mov/el/n-gra.gif">&nbsp;<a href="http://us.rd.yahoo.com/movies/navbar/top/dvd/?http://movies.yahoo.com/dvd/" class="mainoff"><b>DVD / Video</b></a>&nbsp;</td>' );
document.writeln( '<td align=center background="http://us.i1.yimg.com/us.yimg.com/i/us/mov/el/n-gra.gif">&nbsp;<a href="http://us.rd.yahoo.com/movies/navbar/top/mymovies/?http://movies.yahoo.com/profiles/" class="mainoff"><b>My Movies</b></a>&nbsp;</td>' );
document.writeln( '<td align=right valign=top>' );
document.writeln( '<table cellpadding=0 cellspacing=0 border=0>' );
document.writeln( '<tr>' );
document.writeln( '<td>' );
document.writeln( '<span class="fixtext"><b>Search:</b></span>' );
document.writeln( '<select name="search" size="1">' );
document.writeln( '<option value="all">Entire movie database</option>' );
document.writeln( '<option value="title">Movie titles only</option>' );
document.writeln( '<option value="cast">Cast/crew only</option>' );
document.writeln( '<option value="dvd">DVD/Video titles only</option>' );
document.writeln( '<option value="pre">Greg\'s Previews only</option>' );
document.writeln( '<option value="mom">Movie Mom\'s Reviews only</option>' );
document.writeln( '</select>' );
document.writeln( '<span class="fixtext">for</span>' );
document.writeln( '<input size="14" name="p" maxlength="30" type="text">' );
document.writeln( '<input type="submit" value="Search">' );
document.writeln( '<span class="fixtext">&nbsp;</span>' );
document.writeln( '</td>' );
document.writeln( '</tr>' );
document.writeln( '<tr><td height="3"><spacer type=block width=1 height=1></td></tr>' );
document.writeln( '</table>' );
document.writeln( '</td>' );
document.writeln( '</tr>' );
document.writeln( '</form>' );
document.writeln( '</table>' );
document.writeln( '</td></tr></table>' );
document.writeln( '<table border=0 cellpadding=0 cellspacing=0 width=750>' );
document.writeln( '<tr bgcolor=4B6DAD>' );
document.writeln( '<td width=3><img src=http://us.i1.yimg.com/us.yimg.com/i/us/mov/el/n-on-left.gif width=3 height=30 alt=""></td>' );
document.writeln( '<td class=w width=744 align=center><span class="fixtext"></span><a href="http://movies.yahoo.com" class=sub><b>Movies Home</b></a><span class="fixtext">&nbsp;&nbsp;</span><img src="http://us.i1.yimg.com/us.yimg.com/i/us/mov/el/n-pipe.gif" align="absbottom" alt="http://movies.yahoo.com/showtimes/showtimes.html"><span class="fixtext">&nbsp;&nbsp;</span><a href="http://us.rd.yahoo.com/movies/navbar/sub/movies/intheaters/?http://movies.yahoo.com/feature/thisweekend.html" class=sub><b>In Theaters</b></a><span class="fixtext">&nbsp;&nbsp;</span><img src="http://us.i1.yimg.com/us.yimg.com/i/us/mov/el/n-pipe.gif" align="absbottom" alt=""><span class="fixtext">&nbsp;&nbsp;</span><a href="http://us.rd.yahoo.com/movies/navbar/sub/movies/showtimes/?http://movies.yahoo.com/showtimes/showtimes.html" class=sub><b>Showtimes &amp; Tickets</b></a><span class="fixtext">&nbsp;&nbsp;</span><img src="http://us.i1.yimg.com/us.yimg.com/i/us/mov/el/n-pipe.gif" align="absbottom" alt=""><span class="fixtext">&nbsp;&nbsp;</span><a href="http://us.rd.yahoo.com/movies/navbar/sub/movies/comingsoon/?http://movies.yahoo.com/feature/comingsoon.html" class=sub><b>Coming Soon</b></a><span class="fixtext">&nbsp;&nbsp;</span><img src="http://us.i1.yimg.com/us.yimg.com/i/us/mov/el/n-pipe.gif" align="absbottom" alt=""><span class="fixtext">&nbsp;&nbsp;</span><a href="http://us.rd.yahoo.com/movies/navbar/sub/movies/gregs/?http://movies.yahoo.com/upcoming/" class=sub><b>Greg\'s Previews</b></a><span class="fixtext">&nbsp;&nbsp;</span><img src="http://us.i1.yimg.com/us.yimg.com/i/us/mov/el/n-pipe.gif" align="absbottom" alt=""><span class="fixtext"><span class="fixtext">&nbsp;&nbsp;</span><a href="http://us.rd.yahoo.com/movies/navbar/sub/movies/trailers/?http://movies.yahoo.com/trailers/" class=sub><b>Trailers &amp; Clips</b></a><span class="fixtext">&nbsp;&nbsp;</span><img src="http://us.i1.yimg.com/us.yimg.com/i/us/mov/el/n-pipe.gif" align="absbottom" alt=""><span class="fixtext">&nbsp;&nbsp;</span><a href="http://us.rd.yahoo.com/movies/navbar/sub/movies/news/?http://movies.yahoo.com/news/main/" class=sub><b>News</b></a><span class="fixtext">&nbsp;&nbsp;</span><img src="http://us.i1.yimg.com/us.yimg.com/i/us/mov/el/n-pipe.gif" align="absbottom" alt=""><span class="fixtext">&nbsp;&nbsp;</span><a href="http://us.rd.yahoo.com/movies/navbar/sub/movies/boxoffice/?http://movies.yahoo.com/boxoffice/latest/rank.html" class=sub><b>Box Office</b></a><span class="fixtext"></span></td>' );
document.writeln( '<td width=3 align=right><img src=http://us.i1.yimg.com/us.yimg.com/i/us/mov/el/n-on-right.gif width=3 height=30 alt=""></td></tr>' );
document.writeln( '</table>' );
document.writeln( '<table border=0 cellpadding=0 cellspacing=0 width=750>' );
document.writeln( '<tr><td width=750 height=1 bgcolor=33528b><spacer type=block width=1 height=1></td></tr>' );
document.writeln( '<tr><td width=750 height=1 bgcolor=A6B9DC><spacer type=block width=1 height=1></td></tr>' );
document.writeln( '<tr><td width=750 height=1 bgcolor=eeeeee><spacer type=block width=1 height=1></td></tr>' );
document.writeln( '</table>' );
document.writeln( '<!-- /tabs -->' );
